# Generated by Django 4.0 on 2025-07-12 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(unique=True)),
                ('department_id', models.IntegerField(default=0)),
                ('employee_name', models.TextField()),
                ('employee_surname', models.TextField()),
                ('vacation_days', models.IntegerField(default=0)),
                ('date_of_employment', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'data_employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.employee')),
            ],
            options={
                'db_table': 'data_vacation',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='vacation',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', django.db.models.expressions.F('end_date'))), name='valid_vacation_dates'),
        ),
    ]
