# Generated by Django 4.0 on 2025-07-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='vacation',
            table='vacation',
        ),
    ]
